### ISSUE TITLE
Craft functional memo search json per person

### ISSUE THREAD

**Issue by Schiller-Stoff** [memobuch/preprocessing#1]
### DESC
- for indexing custom data to solr e.g. I need to add langitude and lattitude

### LINKs
- https://solr.apache.org/guide/solr/latest/indexing-guide/field-type-definitions-and-properties.html

### TASKs
- [x] find old derla search json --> template on how this json has to look like? --> in y: under "sips"
- [x] solve merge conflict 
- [x] need to add the type person to each object (because there might be objects that contain project material e.g. ABOUT page etc.)
- [x] think about: need to define complex fields in the search.json (separation between label and value!) --> there is no option fir that kind of use case in solr --> the type / assignment needs to be done by "hand" / resolved in the frontend? Nothing that solr directly supports! Nested documents are dangerous because of potential inconsistencies.
- [x] refactor: MemoEvents -> might now link to multiple persons. Refactor in MemoPreprocessing
- [x] MemoEvent should contain a list of categories --> not a string for all --> split beforeHand!
- [x] MemoEvent --> rename category property to categories!
- [x] write types of event to rdfg
- [x] write types of the death event onto the solr person document
- [x] configure set of basic solr fields - defined by the system e.g. for dublin core. And for the generalised mapping to SOLR e.g. gams_type ---> must be an integer?
- [x] fix id problem with memo events: events must be nested in a person's path!
- [x] include rest of properties from RDF onto search.json
- [x] add reference to derla sign to search.json
- [x] craft new SEARCH.json according to these fields for the memo project.
- [x] make sure that SEARCH_INDEX.json is successfully mapped to SOLR
- [x] add dublin core fields in solr manage schema for the gams core! --> dc_title --> etc. 
- [x] think about: add events as standalone entities to the search.json? (Test out to create custom solr entities)
- [x] fix malformed solr date string!
- [x] express semantic in id of digital object, like in hsa: memo.person.12345 etc.
- [ ] use memo.material object: --> think about: resolving categories against a static entiy in solr? --> e.g. a memo-material object could hold anything related to general project aspects. -->  a search.json that defines the categories as some sort of enums with integer values? (with related labeling and stuff)
- [ ] add more tasks
