### ISSUE TITLE
Correct generated RDF for each person

### ISSUE THREAD

**Issue by Schiller-Stoff** [memobuch/preprocessing#2]
### DESC
- RDF is bad atm --> to date was only demo data generated by AI assistant
- z.b. RDF ingested by hgbk project. https://gams.uni-graz.at/archive/objects/o:hgbk.berufe-part-0/datastreams/ONTOLOGY/content

### TASKs
- [x] take a look at generated RDF objects at GAMS3.
- [x] repair dysfunctional attribute statements --> namespaces are missing.
- [x] add rdf:label per person
- [x] test writing via resource.json OR resource.xml? --> I think Gunter is right: this belongs to the sip.json. 
- [x] add longitude / lattitude to the person?
- [x] add more info about a person
- [x] add more tasks

**Comment by Schiller-Stoff** [comment]
implemented
