### ISSUE TITLE
Add processing / handling of documents, images to the memobuch workflow

### ISSUE THREAD

**Issue by Schiller-Stoff** [memobuch/preprocessing#3]
### DESC
- images, documents, etc need also be handled in the memobuch project

###  TASKs
- [ ] setup in google drive
- [ ] add demo data
- [ ] add basic logic to pyhton
- [ ] add more tasks
