### ISSUE TITLE
Add handling of static research data e.g. IMPRINT text etc. 

### ISSUE THREAD

**Issue by Schiller-Stoff** [memobuch/preprocessing#4]
### DESC
- imprint e.g is considered to be a valuable research text to be contained by a digital object e.g. memo.

### TASKs
- [x] add memo.material to handle static project texts (like IMPRINT)
- [x] check if this works with the solr integration
- [x] add more tasks

**Comment by Schiller-Stoff** [comment]
implemented
